version: '3.9'
services:
  ansible_target1:
    image: ubuntu:latest
    container_name: target1
    volumes:
      - ./ubuntu_container_command.sh:/usr/local/bin/container_command.sh
    networks:
      ansible_network:
        ipv4_address: 172.28.1.2
    environment:
      - MY_USERNAME
      - MY_SSH_KEY
    ports:
      - "8082:80"
    command:
      - /bin/bash
      - -c
      - "/usr/local/bin/container_command.sh"

  ansible_target2:
    image: ubuntu:latest
    container_name: target2
    volumes:
      - ./ubuntu_container_command.sh:/usr/local/bin/container_command.sh
    networks:
      ansible_network:
        ipv4_address: 172.28.1.3
    environment:
      - MY_USERNAME
      - MY_SSH_KEY
    ports:
      - "8083:80"
    command:
      - /bin/bash
      - -c
      - "/usr/local/bin/container_command.sh"

  ansible_target3:
    image: ubuntu:latest
    container_name: target3
    volumes:
      - ./ubuntu_container_command.sh:/usr/local/bin/container_command.sh
    networks:
      ansible_network:
        ipv4_address: 172.28.1.4
    environment:
      - MY_USERNAME
      - MY_SSH_KEY
    ports:
      - "8084:80"
    command:
      - /bin/bash
      - -c
      - "/usr/local/bin/container_command.sh"
  
  ansible_target4:
    image: centos:centos7
    container_name: target4
    volumes:
      - ./centos_container_command.sh:/usr/local/bin/container_command.sh
    networks:
      ansible_network:
        ipv4_address: 172.28.1.5
    environment:
      - MY_USERNAME
      - MY_SSH_KEY
    ports:
      - "8085:80"
    command:
      - /bin/bash
      - -c
      - "/usr/local/bin/container_command.sh"

networks:
  ansible_network:
    name: ansible_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
