---

- hosts: all
  become: true
  tasks:

  - name: install apache and php packages 
    package: 
      name: 
        - "{{ apache_package }}" # variable, defined in inventory
        - "{{ php_package }}"
      state: latest
      update_cache: yes
###
  - name: start apache2 for Ubuntu
    command: apache2ctl start
    when: ansible_distribution == "Ubuntu"
###
  - name: start apache for CentOS
    command: /usr/sbin/httpd
    when: ansible_distribution == "CentOS"