---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "7.9"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist 
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages for Ubuntu
    tags: apache, apche2, ubuntu
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  # - name: start apache for Ubuntu
  #   command: apache2ctl start
  #   when: ansible_distribution == "Ubuntu"

  - name: install apache packages for CentOS
    tags: httpd, centos
    yum: 
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "7.9"

  # - name: start apache for CentOS
  #   command: /usr/sbin/httpd
  #   when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:
  - name : install mariadb package (CentOS)
    tags: centos, db, mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "7.9"
  
  # - name: start mariadb for CentOS
  #   command: /usr/bin/mysqld_safe
  #   when: ansible_distribution == "CentOS"

  - name : install mariadb package (Ubuntu)
    tags: ubuntu, db, mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
  
  # - name: start mariadb for Ubuntu
  #   command: mysqld_safe
  #   when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest